update glossary
ArbitrumFoundation/docs pull request #643
Opened 2023-09-08 20:51 UTC by DZGoldman

2023-09-14 23:21 UTC, symbolpunk requested changes
This is awesome - I didn't use the "commit suggestions" for the nits because changes will have to be made in faq cms (happy to update Notion and regen within your branch if you'd prefer)

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +### Will there ever be more than the two current Arbitrum DAO governed chains (Arbitrum DAO and Nova)? {#will-there-ever-be-more-than-the-two-current-arbitrum-dao-governed-chains-arbitrum-dao-and-nov
todo on Notion: `(Arbitrum DAO` -> `(Arbitrum One`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p>Layer 1 chain like Ethereum are ultimately governed by social consensus. L2's like Arbitrum One, by contrast, derive their security from smart contracts on L1; thus, changes to the core system nee
nits todo on Notion: `Layer 1 chain` -> `Layer 1 chains`, `L2's` -> `L2s`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p>An $ARB holder can exclude their votes by delegating to a special exclude address (<a href="https://arbiscan.io/address/0x00000000000000000000000000000000000a4b86">0x000000000000000000000000000000
nit todo on Notion (possible brainfart on my end): `votes count` -> `votes won't count`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p>The $ARB airdrop ends at L1 Ethereum block <a href="https://etherscan.io/block/countdown/18208000">18208000</a> (estimated to be 9/24/23.</p>
nit todo on Notion: `/23.` -> `/23).`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p>An $ARB holder can exclude their votes by delegating to a special exclude address (<a href="https://arbiscan.io/address/0x00000000000000000000000000000000000a4b86">0x000000000000000000000000000000
`largest single holder of ARB` -> `largest single holder of $ARB`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +### What happens to all of the ARB tokens that don't get claimed in the airdrop? {#what-happens-to-all-of-the-arb-tokens-that-dont-get-claimed-in-the-airdrop}
`all of the ARB` -> `all of the $ARB`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p><a href="/dao-glossary#emergency-action">Emergency action</a>s are actions taken by the <a href="/dao-glossary#security-council">Security Council</a> in response to a security emergency, such as a
nit for Notion: `time, are` -> time, Emergency actions are`

2023-09-14 23:21 UTC, symbolpunk commented on docs/partials/_faq-partial.md
> +<p>Yes; voting power can be split between any number of delegtes.</p>
nit for notion: `delegtes` -> `delegates`

2023-09-15 17:48 UTC, DZGoldman commented
> happy to update Notion and regen within your branch if you'd prefer

no this is perfect, I'll make the updates on notion and push, thanks!

2023-09-19 17:24 UTC, symbolpunk approved these changes

2023-09-19 17:24 UTC, merged

2023-11-07 18:52 UTC, anhlam2234 commented
>